# Generated by Django 5.0.2 on 2024-02-24 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='separated_title',
            field=models.TextField(default='Ss'),
            preserve_default=False,
        ),
    ]
