# Generated by Django 5.0.2 on 2024-02-26 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_slider_separated_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='separated_title',
        ),
    ]
