# Generated by Django 5.0.2 on 2024-02-27 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_title_slider_first_title_slider_second_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='bg_image',
            field=models.ImageField(height_field=887, null=True, upload_to='hero-area/', width_field=1600),
        ),
    ]
