# Generated by Django 5.0.2 on 2024-02-27 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_slider_bg_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('image', models.ImageField(max_length=150, upload_to='')),
            ],
        ),
    ]
