# Generated by Django 5.0.2 on 2024-02-27 14:34

from django.db import migrations


class Migration(migrations.Migration):


    dependencies = [
        ('app', '0006_sectionimages'),
    ]

    operations = [
        # migrations.RunPython(),
    ]
