# Generated by Django 5.0.2 on 2024-02-28 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20240227_1834'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sectionimages',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='sectionimages',
            name='image',
            field=models.ImageField(max_length=150, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='slider',
            name='bg_image',
            field=models.ImageField(null=True, upload_to='hero-area/'),
        ),
    ]
