# Generated by Django 5.0.2 on 2024-02-28 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_sectionimages_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionimages',
            name='image',
            field=models.ImageField(max_length=150, null=True, upload_to='section-images/'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='bg_image',
            field=models.ImageField(height_field=887, null=True, upload_to='hero-area/', width_field=1600),
        ),
    ]
