# Generated by Django 5.0.2 on 2024-03-02 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_sectionimages_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='whychooseus',
            options={'ordering': ['id'], 'verbose_name_plural': 'Why Choose Us'},
        ),
        migrations.AddField(
            model_name='whychooseus',
            name='image',
            field=models.ImageField(null=True, upload_to='Why Choose Us Section/'),
        ),
    ]
