# Generated by Django 5.0.2 on 2024-03-02 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_whychooseus_options_whychooseus_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactSection',
        ),
        migrations.AddField(
            model_name='sectionimages',
            name='contact_section',
            field=models.ImageField(null=True, upload_to='SectionImages/ContactSection/'),
        ),
        migrations.AlterField(
            model_name='trainersection',
            name='fb_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainersection',
            name='ig_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainersection',
            name='tw_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
