# Generated by Django 5.0.2 on 2024-03-22 05:53

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_rename_phonr_number_infosection_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infosection',
            name='footer_text',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text'),
        ),
    ]
