# Generated by Django 5.0.2 on 2024-06-12 19:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_infosection_footer_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='sended_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
